services:
  logging:
    image: docker.io/library/ubuntu@sha256:c4a8d5503dfb2a3eb8ab5f807da5bc69a85730fb49b5cfca2330194ebcc41c7b
    volumes:
      - ./logging.pub:/var/logging/logging.pub:ro
      - ./bin/:/var/logging/bin/:ro
    command: bash /var/logging/bin/example.sh
  